"""add_meet_link_and_url_to_activity_events

Revision ID: 9b5cfece90a7
Revises: 2ec382ab7ac3
Create Date: 2026-07-19 16:45:25.584790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5cfece90a7'
down_revision: Union[str, Sequence[str], None] = '2ec382ab7ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('avatar_updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('recovery_codes', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('workspaces', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('workspaces', sa.Column('template_source', sa.String(length=100), nullable=True))
    op.add_column('activity_events', sa.Column('meet_link', sa.Text(), nullable=True))
    op.add_column('activity_events', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_events', 'url')
    op.drop_column('activity_events', 'meet_link')
    op.drop_column('workspaces', 'template_source')
    op.drop_column('workspaces', 'tags')
    op.drop_column('workspaces', 'size')
    op.drop_column('workspaces', 'industry')
    op.drop_column('workspaces', 'website')
    op.drop_column('workspaces', 'logo_url')
    op.drop_column('users', 'recovery_codes')
    op.drop_column('users', 'avatar_updated_at')
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    # ### end Alembic commands ###
